django_projects/locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [path('', views.index, name='index')]

django_projects/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



"""locallibrary URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_projects/locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _l
import uuid
from .constants import LOAN_STATUS 

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text=_l('Nhập thể loại sách (ví dụ: Khoa học viễn tưởng)'))

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text=_l('Nhập mô tả ngắn gọn về cuốn sách'))
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text=_l('13 ký tự <a href="https://www.isbn-international.org/content/what-isbn">mã số ISBN</a>'))
    genre = models.ManyToManyField(Genre, help_text=_l('Chọn một thể loại cho cuốn sách này'))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    """Mô hình đại diện cho một bản sao cụ thể của một cuốn sách (tức là có thể được mượn từ thư viện)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text=_l('ID duy nhất cho cuốn sách này trong toàn bộ thư viện'))
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)


    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text=_l('Tình trạng sách'),
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """Chuỗi đại diện cho đối tượng Model"""
        return f'{self.id} ({self.book.title})'

class Author(models.Model):
    """Mô hình đại diện cho một tác giả."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Mất', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Trả về URL để truy cập một tác giả cụ thể."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """Chuỗi đại diện cho đối tượng Model"""
        return f'{self.last_name}, {self.first_name}'

django_projects/locallibrary/catalog/forms.py
from django import forms
from catalog.models import BookInstance
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text=_("Enter a date between now and 4 weeks (default 3)."))

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data
    
class RenewBookModelForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

django_projects/locallibrary/catalog/views.py
from django.shortcuts import render

# Create your views here.
from catalog.models import Book, Author, BookInstance, Genre
def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors
    }
    return render(request, 'index.html', context=context)

django_projects/locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}<title>Local Library</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
         {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="">All books</a></li>
                        <li><a href="">All authors</a></li>
                    </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
            </div>
        </div>
    </body>
</html>

django_projects/locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Author</h1>
  <p>Are you sure you want to delete the author '{{ author }}'?</p>

  <form method="post" action="{% url 'author-delete' author.id %}">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %} 
{% block content %}
  <h1>Author</h1>
  <p><strong>First name:</strong>{{ author.first_name }}</a></p>
  <p><strong>last_name:</strong> {{ author.last_name }}</p>
  <p><strong>date_of_birth:</strong> {{ author.date_of_birth }}</p>
  <p><strong>date_of_death:</strong> {{ author.date_of_death }}</p>
  <div style="margin-top: 20px">
    <h2>Books by {{ author }}</h2>
    <ul>
        {% for book in books %}
            <li> <a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        {% empty %}
            <li>No books available for this author.</li>
        {% endfor %}
    </ul>
  </div>

{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">{{ author }}</a>
      {% if perms.catalog.change_bookinstance %}
        <a href="{% url 'authors-update' pk=author.pk %}" class="text-warning">Update</a>
        <a href="{% url 'authors-delete' pk=author.pk %}" class="text-danger">Delete</a>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>There are author in the library.</p>
  {% endif %}
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% block content %}
<h1>Title: {{ book.title }}</h1>
<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> 
<!-- author detail linknot yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>
<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm'%}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
        <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew Book: {{ book_instance.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <p><input type="submit" value="Submit" /></p>
  </form>
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>Borrowed books</h1>
  
  {% if bookinstance_list %}
  <ul>
    {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrower }}
        {% if perms.catalog.can_mark_returned %}
          <form method="post" action="{% url 'renew-book-librarian' bookinst.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-link">Renew</button>
          </form>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No books currently borrowed.</p>
  {% endif %}
{% endblock %}

django_projects/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>
    
    {% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{bookinst.due_back }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

django_projects/locallibrary/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Local Library Home</h1>
    <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong>{{num_authors}}</li>
    </ul>
{% endblock %}